// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.6
// source: proto/comments.proto

package ch11

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Sent          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=sent,proto3" json:"sent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentRequest) Reset() {
	*x = CommentRequest{}
	mi := &file_proto_comments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentRequest) ProtoMessage() {}

func (x *CommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentRequest.ProtoReflect.Descriptor instead.
func (*CommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_comments_proto_rawDescGZIP(), []int{0}
}

func (x *CommentRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CommentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CommentRequest) GetSent() *timestamppb.Timestamp {
	if x != nil {
		return x.Sent
	}
	return nil
}

type CommentResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CommentLength        int32                  `protobuf:"varint,1,opt,name=commentLength,proto3" json:"commentLength,omitempty"`
	PreviousCommentCount int32                  `protobuf:"varint,2,opt,name=previousCommentCount,proto3" json:"previousCommentCount,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CommentResponse) Reset() {
	*x = CommentResponse{}
	mi := &file_proto_comments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentResponse) ProtoMessage() {}

func (x *CommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentResponse.ProtoReflect.Descriptor instead.
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_comments_proto_rawDescGZIP(), []int{1}
}

func (x *CommentResponse) GetCommentLength() int32 {
	if x != nil {
		return x.CommentLength
	}
	return 0
}

func (x *CommentResponse) GetPreviousCommentCount() int32 {
	if x != nil {
		return x.PreviousCommentCount
	}
	return 0
}

var File_proto_comments_proto protoreflect.FileDescriptor

const file_proto_comments_proto_rawDesc = "" +
	"\n" +
	"\x14proto/comments.proto\x12\x04chat\x1a\x1fgoogle/protobuf/timestamp.proto\"p\n" +
	"\x0eCommentRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12.\n" +
	"\x04sent\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04sent\"k\n" +
	"\x0fCommentResponse\x12$\n" +
	"\rcommentLength\x18\x01 \x01(\x05R\rcommentLength\x122\n" +
	"\x14previousCommentCount\x18\x02 \x01(\x05R\x14previousCommentCount2M\n" +
	"\vChatService\x12>\n" +
	"\rRouteComments\x12\x14.chat.CommentRequest\x1a\x15.chat.CommentResponse\"\x00B\bZ\x06./ch11b\x06proto3"

var (
	file_proto_comments_proto_rawDescOnce sync.Once
	file_proto_comments_proto_rawDescData []byte
)

func file_proto_comments_proto_rawDescGZIP() []byte {
	file_proto_comments_proto_rawDescOnce.Do(func() {
		file_proto_comments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_comments_proto_rawDesc), len(file_proto_comments_proto_rawDesc)))
	})
	return file_proto_comments_proto_rawDescData
}

var file_proto_comments_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_comments_proto_goTypes = []any{
	(*CommentRequest)(nil),        // 0: chat.CommentRequest
	(*CommentResponse)(nil),       // 1: chat.CommentResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_comments_proto_depIdxs = []int32{
	2, // 0: chat.CommentRequest.sent:type_name -> google.protobuf.Timestamp
	0, // 1: chat.ChatService.RouteComments:input_type -> chat.CommentRequest
	1, // 2: chat.ChatService.RouteComments:output_type -> chat.CommentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_comments_proto_init() }
func file_proto_comments_proto_init() {
	if File_proto_comments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_comments_proto_rawDesc), len(file_proto_comments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_comments_proto_goTypes,
		DependencyIndexes: file_proto_comments_proto_depIdxs,
		MessageInfos:      file_proto_comments_proto_msgTypes,
	}.Build()
	File_proto_comments_proto = out.File
	file_proto_comments_proto_goTypes = nil
	file_proto_comments_proto_depIdxs = nil
}
